name: QA

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"
  workflow_call:
  workflow_dispatch:

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main
